name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Build project
      run: dotnet restore

    - name: Build project
      run: dotnet build

    - name: Run unit tests
      run: dotnet test
    
    - name: Run script manually
      if: github.event_name == 'manual_trigger'
      run: dotnet build && dotnet test

